"""
Configuration management for Weather CLI
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv


@dataclass
class Settings:
    """Application settings with environment variable support"""

    # API Keys
    windy_api_key: Optional[str] = None

    # Default settings
    default_city: str = "beijing"
    units: str = "metric"  # metric or imperial
    forecast_days: int = 3

    # Display settings
    show_emoji: bool = True
    show_ascii: bool = True
    color_output: bool = True

    # Config paths
    config_dir: Path = field(default_factory=lambda: Path.home() / ".config" / "weather-cli")

    def __post_init__(self):
        # Load from .env file
        self._load_env()

        # Override with environment variables
        if os.environ.get("WINDY_API_KEY"):
            self.windy_api_key = os.environ["WINDY_API_KEY"]
        if os.environ.get("WEATHER_DEFAULT_CITY"):
            self.default_city = os.environ["WEATHER_DEFAULT_CITY"]
        if os.environ.get("WEATHER_UNITS"):
            self.units = os.environ["WEATHER_UNITS"]

    def _load_env(self):
        """Load environment from config file"""
        env_file = self.config_dir / ".env"
        if env_file.exists():
            load_dotenv(env_file)

    def save(self):
        """Save current settings to config file"""
        self.config_dir.mkdir(parents=True, exist_ok=True)
        env_file = self.config_dir / ".env"

        lines = [
            f"# Weather CLI Configuration",
            f"# Generated by weather-cli",
            f"",
            f"WINDY_API_KEY={self.windy_api_key or ''}",
            f"WEATHER_DEFAULT_CITY={self.default_city}",
            f"WEATHER_UNITS={self.units}",
        ]

        env_file.write_text("\n".join(lines))

    @classmethod
    def load(cls) -> "Settings":
        """Load settings from config file"""
        return cls()


# Global settings instance
settings = Settings.load()


# Supported cities with coordinates
CITIES = {
    "beijing": {"lat": 39.9042, "lon": 116.4074, "timezone": "Asia/Shanghai", "country": "CN"},
    "shanghai": {"lat": 31.2304, "lon": 121.4737, "timezone": "Asia/Shanghai", "country": "CN"},
    "shenzhen": {"lat": 22.5431, "lon": 114.0579, "timezone": "Asia/Shanghai", "country": "CN"},
    "guangzhou": {"lat": 23.1291, "lon": 113.2644, "timezone": "Asia/Shanghai", "country": "CN"},
    "chengdu": {"lat": 30.5728, "lon": 104.0668, "timezone": "Asia/Shanghai", "country": "CN"},
    "xian": {"lat": 34.3416, "lon": 108.9398, "timezone": "Asia/Shanghai", "country": "CN"},
    "wuhan": {"lat": 30.5928, "lon": 114.3055, "timezone": "Asia/Shanghai", "country": "CN"},
    "nanjing": {"lat": 32.0603, "lon": 118.7969, "timezone": "Asia/Shanghai", "country": "CN"},
    "hangzhou": {"lat": 30.2741, "lon": 120.1551, "timezone": "Asia/Shanghai", "country": "CN"},
    "chongqing": {"lat": 29.4316, "lon": 106.9123, "timezone": "Asia/Shanghai", "country": "CN"},
    "kunming": {"lat": 25.0389, "lon": 102.7183, "timezone": "Asia/Shanghai", "country": "CN"},
    "shangri-la": {"lat": 27.8, "lon": 99.7, "timezone": "Asia/Shanghai", "country": "CN"},
    "newyork": {"lat": 40.7128, "lon": -74.0060, "timezone": "America/New_York", "country": "US"},
    "london": {"lat": 51.5074, "lon": -0.1278, "timezone": "Europe/London", "country": "GB"},
    "tokyo": {"lat": 35.6762, "lon": 139.6503, "timezone": "Asia/Tokyo", "country": "JP"},
    "paris": {"lat": 48.8566, "lon": 2.3522, "timezone": "Europe/Paris", "country": "FR"},
    "sydney": {"lat": -33.8688, "lon": 151.2093, "timezone": "Australia/Sydney", "country": "AU"},
}

# WMO weather codes to descriptions
WEATHER_CODES = {
    # Clear and cloudy
    0: ("Clear sky", "☀️", "晴"),
    1: ("Mainly clear", "🌤️", "大部晴朗"),
    2: ("Partly cloudy", "⛅", "多云"),
    3: ("Overcast", "☁️", "阴天"),
    # Fog
    45: ("Fog", "🌫️", "雾"),
    48: ("Depositing rime fog", "🌫️", "雾凇"),
    # Drizzle
    51: ("Light drizzle", "🌧️", "微毛毛雨"),
    53: ("Moderate drizzle", "🌧️", "毛毛雨"),
    55: ("Dense drizzle", "🌧️", "大毛毛雨"),
    56: ("Light freezing drizzle", "🌨️", "轻微冻毛毛雨"),
    57: ("Dense freezing drizzle", "🌨️", "浓冻毛毛雨"),
    # Rain
    61: ("Slight rain", "🌧️", "小雨"),
    63: ("Moderate rain", "🌧️", "中雨"),
    65: ("Heavy rain", "🌧️", "大雨"),
    66: ("Light freezing rain", "🌨️", "轻微冻雨"),
    67: ("Heavy freezing rain", "🌨️", "大冻雨"),
    # Snow
    71: ("Slight snow", "🌨️", "小雪"),
    73: ("Moderate snow", "🌨️", "中雪"),
    75: ("Heavy snow", "❄️", "大雪"),
    77: ("Snow grains", "🌨️", "雪粒"),
    # Rain showers
    80: ("Slight rain showers", "🌦️", "小阵雨"),
    81: ("Moderate rain showers", "🌦️", "阵雨"),
    82: ("Violent rain showers", "⛈️", "大阵雨"),
    # Snow showers
    85: ("Slight snow showers", "🌨️", "小阵雪"),
    86: ("Heavy snow showers", "❄️", "大阵雪"),
    # Thunderstorm
    95: ("Thunderstorm", "⛈️", "雷暴"),
    96: ("Thunderstorm with slight hail", "⛈️", "雷暴伴小冰雹"),
    99: ("Thunderstorm with heavy hail", "⛈️", "雷暴伴大冰雹"),
}
